// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	GetTodo(ctx context.Context, id uuid.UUID) (Todo, error)
	ListTodos(ctx context.Context) ([]Todo, error)
	// Insert-or-replace, honoring the todo.Repository.Save upsert contract.
	UpsertTodo(ctx context.Context, arg UpsertTodoParams) error
}

var _ Querier = (*Queries)(nil)
