// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/meigma/template-go-api/internal/todo"
	mock "github.com/stretchr/testify/mock"
)

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// FindByID provides a mock function for the type Repository
func (_mock *Repository) FindByID(ctx context.Context, id string) (todo.Todo, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 todo.Todo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (todo.Todo, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) todo.Todo); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(todo.Todo)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type Repository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *Repository_Expecter) FindByID(ctx any, id any) *Repository_FindByID_Call {
	return &Repository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *Repository_FindByID_Call) Run(run func(ctx context.Context, id string)) *Repository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_FindByID_Call) Return(todo1 todo.Todo, err error) *Repository_FindByID_Call {
	_c.Call.Return(todo1, err)
	return _c
}

func (_c *Repository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id string) (todo.Todo, error)) *Repository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type Repository
func (_mock *Repository) List(ctx context.Context, page todo.PageQuery) (todo.PageResult, error) {
	ret := _mock.Called(ctx, page)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 todo.PageResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, todo.PageQuery) (todo.PageResult, error)); ok {
		return returnFunc(ctx, page)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, todo.PageQuery) todo.PageResult); ok {
		r0 = returnFunc(ctx, page)
	} else {
		r0 = ret.Get(0).(todo.PageResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, todo.PageQuery) error); ok {
		r1 = returnFunc(ctx, page)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type Repository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - page todo.PageQuery
func (_e *Repository_Expecter) List(ctx any, page any) *Repository_List_Call {
	return &Repository_List_Call{Call: _e.mock.On("List", ctx, page)}
}

func (_c *Repository_List_Call) Run(run func(ctx context.Context, page todo.PageQuery)) *Repository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 todo.PageQuery
		if args[1] != nil {
			arg1 = args[1].(todo.PageQuery)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_List_Call) Return(pageResult todo.PageResult, err error) *Repository_List_Call {
	_c.Call.Return(pageResult, err)
	return _c
}

func (_c *Repository_List_Call) RunAndReturn(run func(ctx context.Context, page todo.PageQuery) (todo.PageResult, error)) *Repository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type Repository
func (_mock *Repository) Save(ctx context.Context, todo1 todo.Todo) error {
	ret := _mock.Called(ctx, todo1)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, todo.Todo) error); ok {
		r0 = returnFunc(ctx, todo1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Repository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type Repository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - todo1 todo.Todo
func (_e *Repository_Expecter) Save(ctx any, todo1 any) *Repository_Save_Call {
	return &Repository_Save_Call{Call: _e.mock.On("Save", ctx, todo1)}
}

func (_c *Repository_Save_Call) Run(run func(ctx context.Context, todo1 todo.Todo)) *Repository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 todo.Todo
		if args[1] != nil {
			arg1 = args[1].(todo.Todo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_Save_Call) Return(err error) *Repository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Repository_Save_Call) RunAndReturn(run func(ctx context.Context, todo1 todo.Todo) error) *Repository_Save_Call {
	_c.Call.Return(run)
	return _c
}
