// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/danielgtaylor/huma/v2"
	"github.com/meigma/template-go-api/internal/authz"
	mock "github.com/stretchr/testify/mock"
)

// NewAuthenticator creates a new instance of Authenticator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthenticator(t interface {
	mock.TestingT
	Cleanup(func())
}) *Authenticator {
	mock := &Authenticator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Authenticator is an autogenerated mock type for the Authenticator type
type Authenticator struct {
	mock.Mock
}

type Authenticator_Expecter struct {
	mock *mock.Mock
}

func (_m *Authenticator) EXPECT() *Authenticator_Expecter {
	return &Authenticator_Expecter{mock: &_m.Mock}
}

// Authenticate provides a mock function for the type Authenticator
func (_mock *Authenticator) Authenticate(ctx huma.Context) (authz.Principal, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 authz.Principal
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(huma.Context) (authz.Principal, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(huma.Context) authz.Principal); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(authz.Principal)
	}
	if returnFunc, ok := ret.Get(1).(func(huma.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Authenticator_Authenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authenticate'
type Authenticator_Authenticate_Call struct {
	*mock.Call
}

// Authenticate is a helper method to define mock.On call
//   - ctx huma.Context
func (_e *Authenticator_Expecter) Authenticate(ctx any) *Authenticator_Authenticate_Call {
	return &Authenticator_Authenticate_Call{Call: _e.mock.On("Authenticate", ctx)}
}

func (_c *Authenticator_Authenticate_Call) Run(run func(ctx huma.Context)) *Authenticator_Authenticate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 huma.Context
		if args[0] != nil {
			arg0 = args[0].(huma.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Authenticator_Authenticate_Call) Return(principal authz.Principal, err error) *Authenticator_Authenticate_Call {
	_c.Call.Return(principal, err)
	return _c
}

func (_c *Authenticator_Authenticate_Call) RunAndReturn(run func(ctx huma.Context) (authz.Principal, error)) *Authenticator_Authenticate_Call {
	_c.Call.Return(run)
	return _c
}
