// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/cedar-policy/cedar-go/types"
	mock "github.com/stretchr/testify/mock"
)

// NewEntityResolver creates a new instance of EntityResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEntityResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *EntityResolver {
	mock := &EntityResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// EntityResolver is an autogenerated mock type for the EntityResolver type
type EntityResolver struct {
	mock.Mock
}

type EntityResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *EntityResolver) EXPECT() *EntityResolver_Expecter {
	return &EntityResolver_Expecter{mock: &_m.Mock}
}

// Resolve provides a mock function for the type EntityResolver
func (_mock *EntityResolver) Resolve(uid types.EntityUID) (types.Entity, bool) {
	ret := _mock.Called(uid)

	if len(ret) == 0 {
		panic("no return value specified for Resolve")
	}

	var r0 types.Entity
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(types.EntityUID) (types.Entity, bool)); ok {
		return returnFunc(uid)
	}
	if returnFunc, ok := ret.Get(0).(func(types.EntityUID) types.Entity); ok {
		r0 = returnFunc(uid)
	} else {
		r0 = ret.Get(0).(types.Entity)
	}
	if returnFunc, ok := ret.Get(1).(func(types.EntityUID) bool); ok {
		r1 = returnFunc(uid)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// EntityResolver_Resolve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resolve'
type EntityResolver_Resolve_Call struct {
	*mock.Call
}

// Resolve is a helper method to define mock.On call
//   - uid types.EntityUID
func (_e *EntityResolver_Expecter) Resolve(uid any) *EntityResolver_Resolve_Call {
	return &EntityResolver_Resolve_Call{Call: _e.mock.On("Resolve", uid)}
}

func (_c *EntityResolver_Resolve_Call) Run(run func(uid types.EntityUID)) *EntityResolver_Resolve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 types.EntityUID
		if args[0] != nil {
			arg0 = args[0].(types.EntityUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *EntityResolver_Resolve_Call) Return(entity types.Entity, b bool) *EntityResolver_Resolve_Call {
	_c.Call.Return(entity, b)
	return _c
}

func (_c *EntityResolver_Resolve_Call) RunAndReturn(run func(uid types.EntityUID) (types.Entity, bool)) *EntityResolver_Resolve_Call {
	_c.Call.Return(run)
	return _c
}

// Types provides a mock function for the type EntityResolver
func (_mock *EntityResolver) Types() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Types")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// EntityResolver_Types_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Types'
type EntityResolver_Types_Call struct {
	*mock.Call
}

// Types is a helper method to define mock.On call
func (_e *EntityResolver_Expecter) Types() *EntityResolver_Types_Call {
	return &EntityResolver_Types_Call{Call: _e.mock.On("Types")}
}

func (_c *EntityResolver_Types_Call) Run(run func()) *EntityResolver_Types_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *EntityResolver_Types_Call) Return(strings []string) *EntityResolver_Types_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *EntityResolver_Types_Call) RunAndReturn(run func() []string) *EntityResolver_Types_Call {
	_c.Call.Return(run)
	return _c
}
