// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/meigma/template-go-api/internal/authz/apikey"
	mock "github.com/stretchr/testify/mock"
)

// NewAPIKeyStore creates a new instance of APIKeyStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAPIKeyStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *APIKeyStore {
	mock := &APIKeyStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// APIKeyStore is an autogenerated mock type for the APIKeyStore type
type APIKeyStore struct {
	mock.Mock
}

type APIKeyStore_Expecter struct {
	mock *mock.Mock
}

func (_m *APIKeyStore) EXPECT() *APIKeyStore_Expecter {
	return &APIKeyStore_Expecter{mock: &_m.Mock}
}

// Lookup provides a mock function for the type APIKeyStore
func (_mock *APIKeyStore) Lookup(ctx context.Context, key string) (apikey.Identity, bool, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Lookup")
	}

	var r0 apikey.Identity
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (apikey.Identity, bool, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) apikey.Identity); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(apikey.Identity)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, key)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// APIKeyStore_Lookup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Lookup'
type APIKeyStore_Lookup_Call struct {
	*mock.Call
}

// Lookup is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *APIKeyStore_Expecter) Lookup(ctx any, key any) *APIKeyStore_Lookup_Call {
	return &APIKeyStore_Lookup_Call{Call: _e.mock.On("Lookup", ctx, key)}
}

func (_c *APIKeyStore_Lookup_Call) Run(run func(ctx context.Context, key string)) *APIKeyStore_Lookup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *APIKeyStore_Lookup_Call) Return(identity apikey.Identity, b bool, err error) *APIKeyStore_Lookup_Call {
	_c.Call.Return(identity, b, err)
	return _c
}

func (_c *APIKeyStore_Lookup_Call) RunAndReturn(run func(ctx context.Context, key string) (apikey.Identity, bool, error)) *APIKeyStore_Lookup_Call {
	_c.Call.Return(run)
	return _c
}
