// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type ApiKey struct {
	Key     string
	Subject string
	Roles   []string
}

type Todo struct {
	ID          uuid.UUID
	Title       string
	Status      string
	CreatedAt   time.Time
	CompletedAt *time.Time
}
