// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	GetTodo(ctx context.Context, id uuid.UUID) (Todo, error)
	// Keyset (cursor) pagination over the (created_at, id) ordering. The after_*
	// bound is NULL on the first page; otherwise the row-value comparison resumes
	// strictly after the prior page's last row. page_limit caps the rows scanned;
	// callers fetch one extra to detect whether a further page exists. The composite
	// index on (created_at, id) (see 00001_create_todos.sql) makes the seek
	// index-backed.
	ListTodos(ctx context.Context, arg ListTodosParams) ([]Todo, error)
	// Insert-or-replace by primary key.
	UpsertTodo(ctx context.Context, arg UpsertTodoParams) error
}

var _ Querier = (*Queries)(nil)
