// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: todos.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getTodo = `-- name: GetTodo :one
SELECT id, title, status, created_at, completed_at FROM todos WHERE id = $1
`

func (q *Queries) GetTodo(ctx context.Context, id uuid.UUID) (Todo, error) {
	row := q.db.QueryRow(ctx, getTodo, id)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listTodos = `-- name: ListTodos :many
SELECT id, title, status, created_at, completed_at FROM todos
WHERE (
    $1::timestamptz IS NULL
    OR (created_at, id) > ($1::timestamptz, $2::uuid)
)
ORDER BY created_at, id
LIMIT $3
`

type ListTodosParams struct {
	AfterCreatedAt *time.Time
	AfterID        pgtype.UUID
	PageLimit      int32
}

// Keyset (cursor) pagination over the (created_at, id) ordering. The after_*
// bound is NULL on the first page; otherwise the row-value comparison resumes
// strictly after the prior page's last row. page_limit caps the rows scanned;
// callers fetch one extra to detect whether a further page exists. The composite
// index on (created_at, id) (see 00001_create_todos.sql) makes the seek
// index-backed.
func (q *Queries) ListTodos(ctx context.Context, arg ListTodosParams) ([]Todo, error) {
	rows, err := q.db.Query(ctx, listTodos, arg.AfterCreatedAt, arg.AfterID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Status,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTodo = `-- name: UpsertTodo :exec
INSERT INTO todos (id, title, status, created_at, completed_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (id) DO UPDATE
  SET title = EXCLUDED.title,
      status = EXCLUDED.status,
      created_at = EXCLUDED.created_at,
      completed_at = EXCLUDED.completed_at
`

type UpsertTodoParams struct {
	ID          uuid.UUID
	Title       string
	Status      string
	CreatedAt   time.Time
	CompletedAt *time.Time
}

// Insert-or-replace by primary key.
func (q *Queries) UpsertTodo(ctx context.Context, arg UpsertTodoParams) error {
	_, err := q.db.Exec(ctx, upsertTodo,
		arg.ID,
		arg.Title,
		arg.Status,
		arg.CreatedAt,
		arg.CompletedAt,
	)
	return err
}
